---
- name: Gather needed facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "user"
      - "!min"
  when: >
    ansible_distribution_release is not defined
    or ansible_user_id is not defined

- name: Add Docker apt-key
  become: true
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    keyring: /etc/apt/keyrings/docker.gpg

- name: Add Docker repository
  become: true
  ansible.builtin.apt_repository:
    repo: >
      deb
      [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg]
      https://download.docker.com/linux/ubuntu
      {{ ansible_distribution_release }}
      stable

- name: Install Docker
  become: true
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-compose

- name: "Add docker group"
  become: true
  ansible.builtin.group:
    name: docker
    system: true

- name: "Add the current user to the docker group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true

- name: Stat the docker daemon socket
  ansible.builtin.stat:
    path: /var/run/docker.sock
  register: docker_sock

- name: Restart docker service
  become: true
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
    daemon_reload: true
  when: (not docker_sock.stat.exists) or
        (not docker_sock.stat.gr_name == 'docker')
  tags:
    - systemd
