---
- name: Install pdftk
  become: true
  ansible.builtin.apt:
    name:
      - pdftk

- name: Install Duplex script
  ansible.builtin.copy:
    src: "Duplex from non-duplex ADF scanner"
    dest: ~/.local/share/nautilus/scripts/
    mode: '0755'
