- name: Install awscli and s3cmd
  pip:
    name:
      - awscli ~= {{ awscli_version_match }}
      - s3cmd ~= {{ s3cmd_version_match }}
    state: latest

- name: Install aws-iam-authenticator
  get_url:
    url: https://amazon-eks.s3-us-west-2.amazonaws.com/{{ aws_iam_authenticator_version }}/bin/linux/amd64/aws-iam-authenticator
    dest: ~/bin/aws-iam-authenticator
    mode: 0755
