- name: Add Microsoft repository
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main

- name: Install Azure CLI
  become: true
  apt:
    pkg:
      - azure-cli
