---
- name: Gather needed facts
  ansible.builtin.setup:
    gather_subset:
      - "distribution"
      - "!min"
  when: ansible_distribution_release is not defined

- name: Add Microsoft repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main

- name: Install Azure CLI
  become: true
  ansible.builtin.apt:
    pkg:
      - azure-cli
