- name: Download rclone.deb
  get_url:
    url: https://downloads.rclone.org/v1.65.0/rclone-v1.65.0-linux-amd64.deb
    dest: /tmp/rclone.deb

- name: Install rclone
  become: true
  apt:
    deb: /tmp/rclone.deb
