- name: Install mplayer
  become: true
  apt:
    name: mplayer

- name: Create mplayer configuration folder
  file:
    path: ~/.mplayer
    state: directory

- name: Configure mplayer
  template:
    src: mplayer_config.j2
    dest: ~/.mplayer/config
