---
- name: Install mplayer
  become: true
  ansible.builtin.apt:
    name: mplayer

- name: Create mplayer configuration folder
  ansible.builtin.file:
    path: ~/.mplayer
    state: directory
    mode: '0755'

- name: Configure mplayer
  ansible.builtin.template:
    src: mplayer_config.j2
    dest: ~/.mplayer/config
    mode: '0644'
