---
- name: Install admin tools
  become: true
  ansible.builtin.apt:
    name:
      - curl
      - htop
      - inotify-tools
      - iperf
      - iotop
      - jq
      - mc
      - moreutils
      - net-tools
      - pv
      - screen
      - tcptrack
      - uuid
      - zip
