helm_version: 3.8.0

kubectl_version: 1.23.3
kubectx_version: 0.9.4
kubens_version: 0.9.4
krew_version: 0.4.3

terraform_version: 1.1.4

sops_version: 3.7.1

krew_plugins:
  - name: oidc-login
    creates: ~/.krew/bin/kubectl-oidc_login
