helm_version: 3.8.0

kubectl_version: 1.28.3
kubectx_version: 0.9.5
kubens_version: 0.9.5
krew_version: 0.4.4
sops_version: 3.8.1

terraform_version: 1.1.4

krew_plugins:
  - name: oidc-login
    creates: ~/.krew/bin/kubectl-oidc_login
