- name: Install binaries
  get_url:
    url: '{{ item }}'
    dest: '~/bin/{{ item | basename }}'
    mode: 0755
  loop:
    - https://raw.githubusercontent.com/ahmetb/kubectx/{{ kubectx_version }}/kubectx
    - https://raw.githubusercontent.com/ahmetb/kubectx/{{ kubens_version }}/kubens
    - https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64/kubectl

- name: Install helm
  unarchive:
    src: https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz
    dest: ~/bin
    creates: ~/bin/helm
    remote_src: yes
    extra_opts:
      - --strip-components=1
      - --wildcards
      - '*/helm'

- name: Install terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: ~/bin
    creates: ~/bin/terraform
    remote_src: yes
