---
- name: Install binaries
  ansible.builtin.get_url:
    url: '{{ item }}'
    dest: '~/bin/{{ item | basename }}'
    mode: '0755'
  loop:
    - https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/kubectx
    - https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubens_version }}/kubens
    - https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl

- name: Install krew
  ansible.builtin.shell: |
    (
      set -xo pipefail; cd "$(mktemp -d)" &&
      OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
      ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
      KREW="krew-${OS}_${ARCH}" &&
      curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
      tar zxvf "${KREW}.tar.gz" &&
      ./"${KREW}" install krew
    )
  args:
    executable: /bin/bash
    creates: ~/.krew/bin

- name: Install krew plugins
  ansible.builtin.shell: |
    PATH="$HOME/bin:$HOME/.krew/bin:$PATH"
    kubectl krew install {{ item.name }}
  args:
    creates: '{{ item.creates }}'
  loop: '{{ krew_plugins }}'

- name: Install helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
    dest: ~/bin
    creates: ~/bin/helm
    remote_src: true
    extra_opts:
      - --strip-components=1
      - --wildcards
      - '*/helm'

- name: Install terraform
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
    dest: ~/bin
    creates: ~/bin/terraform
    remote_src: true

- name: Install sops
  become: true
  ansible.builtin.apt:
    name: sops
