language: bash

services:
  - docker

env:
  - ROLE=
  - ROLE=cklein.cloud_tools
  - ROLE=cklein.cncf
  - ROLE=cklein.git
  - ROLE=cklein.security
  - ROLE=cklein.shell
  - ROLE=workstation

stages:
  - lint
  - test

jobs:
  include:
    - script: ./lint.sh
      stage: lint
      env: # no matrix expansion
    - script:
        - ./scripts/generate-site-yml-for-role.sh
        - ./test.sh
