language: bash

services:
  - docker

env:
  - ANSIBLE_PLAYBOOK=site.yml
  - ANSIBLE_PLAYBOOK=test/cklein.cncf.yaml
  - ANSIBLE_PLAYBOOK=test/cklein.git.yaml
  - ANSIBLE_PLAYBOOK=test/cklein.security.yaml
  - ANSIBLE_PLAYBOOK=test/cklein.shell.yaml
  - ANSIBLE_PLAYBOOK=test/workstation.yaml

script:
  - ./test.sh
