language: bash

services:
  - docker

env:
  - ROLE=
  - ROLE=cklein.cncf
  - ROLE=cklein.git
  - ROLE=cklein.security
  - ROLE=cklein.shell
  - ROLE=cklein.workstation

script:
  - ./scripts/generate-site-yml-for-role.sh
  - ./test.sh
