language: bash

services:
  - docker

env:
  - ROLE=
  - ROLE=cklein.cloud_tools
  - ROLE=cklein.cncf
  - ROLE=cklein.git
  - ROLE=cklein.go
  - ROLE=cklein.security
  - ROLE=cklein.shell
  - ROLE=workstation

stages:
  - lint
  - test

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./scripts/generate-site-yml-for-role.sh
  - ./test.sh

jobs:
  include:
    - script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - ./lint.sh
      stage: lint
      # no matrix expansion
      env: ROLE=
