language: bash

services:
  - docker

env:
  - ROLE=
  - ROLE=cklein.cloud_tools
  - ROLE=cklein.cncf
  - ROLE=cklein.git
  - ROLE=cklein.go
  - ROLE=cklein.security
  - ROLE=cklein.shell
  - ROLE=workstation

stages:
  - lint
  - test

script:
  - ./scripts/generate-site-yml-for-role.sh
  - ./test.sh

jobs:
  include:
    - script: ./lint.sh
      stage: lint
      # no matrix expansion
      env: ROLE=
