- name: set up localhost as workstation
  hosts: localhost
  connection: local
  module_defaults:
    apt:
      force_apt_get: yes
    pip:
      executable: pip3
      extra_args: --user
  roles:
    # Prefer first to trigger changes in case of incorrect errata
    - cklein.errata

    - cklein.admin_tools
    - cklein.c
    - cklein.cad
    - cklein.cloud_tools
    - cklein.cncf
    - cklein.default_apps
    - cklein.dictionaries
    - cklein.docker
    - cklein.dotnet
    - cklein.dropbox
    - cklein.git
    - cklein.go
    - cklein.hugo
    - cklein.imagemagick
    - cklein.minikube
    - cklein.mutt
    - cklein.mplayer
    - cklein.nodejs
    - cklein.python
    - cklein.remote_unlock_encrypted_volume
    - cklein.security
    - cklein.shell
    - cklein.slack
    - cklein.spotify
    - cklein.terminator
    - cklein.vscode
    - cklein.vim
    - cklein.tmp_on_tmpfs
    - cklein.zoom
    - workstation
    # Best to run after all favorite apps are installed
    - cklein.gnome_favorite_apps

    # Leave as last for proper cleanup
    - cklein.zz_cleanup
