- name: set up localhost as workstation
  hosts: localhost
  connection: local
  roles:
    - workstation
  vars:
    sshkeys:
      - "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAmJNTPvYo4jPr9zTlGfbqEbFE2fJn/QxLOY/mLB0ANvlTi2/5JvCqwI1jNusjQTQmEnp5wj3XlKR2Yh0W2IrKUStej2xMqWb85r5jzMKzm//DuyRpm8s1dKkmst3g7fPd3DYyy3ZkmCaY6rBBAkluZMR0uCUdHnbtIjCUlbilKCyXUD6ZptIUl7yIj0a+trxLOPIAXynupqE8ufrjXQqPPClD/xgV49HidMT0rrwIQEr502/afFJIKxzE9rBcBwzJ0rzEKZg8G70npXBpzsdaqvsQPLlNatUSvA8g2ed7YzmrbnoMV2XMu6jvztEDTn8UQNV9/VWTnO1iJyhI62d77w== cristi@hades"
