- name: set up localhost as workstation
  hosts: localhost
  connection: local
  module_defaults:
    apt:
      force_apt_get: yes
    pip:
      executable: pip3
      extra_args: --user
  roles:
    - cklein.admin_tools
    - cklein.cloud_tools
    - cklein.cncf
    - cklein.git
    - cklein.go
    - cklein.python
    - cklein.remote_unlock_encrypted_volume
    - cklein.security
    - cklein.shell
    - cklein.vscode
    - cklein.vim
    - workstation
    # Best to run after all favorite apps are installed
    - cklein.gnome_favorite_apps

    # Leave as last for proper cleanup
    - cklein.zz_cleanup
