---
- name: Set up localhost as workstation
  hosts: localhost
  connection: local
  module_defaults:
    apt:
      force_apt_get: true
  roles:
    # Prefer first to trigger changes in case of incorrect errata
    - cklein.errata

    - cklein.admin_tools
    - cklein.c
    - cklein.cloud_tools
    - cklein.cncf
    - cklein.chrome
    - role: cklein.chrome-extra-profiles
      tags: chrome-extra-profiles
      vars:
        profile_names:
          - elastisys
          - le-staging
          - t
    - cklein.default_apps
    - cklein.dictionaries
    - cklein.docker
    - cklein.dotfiles
    - cklein.dotnet
    - cklein.dropbox
    - cklein.fonts
    - cklein.git
    - cklein.go
    - cklein.hugo
    - cklein.imagemagick
    - cklein.mutt
    - cklein.mplayer
    - cklein.nodejs
    - cklein.ntp.se
    - cklein.obsidian
    - cklein.pdftk
    - cklein.python
    - cklein.remote_unlock_encrypted_volume
    - cklein.security
    - cklein.spotify
    - cklein.terminator
    - cklein.vscode
    - cklein.vim
    - cklein.wallpapers
    - cklein.webcam_fix
    - cklein.tmp_on_tmpfs
    # - cklein.zoom
    # Best to run after all favorite apps are installed
    - role: cklein.gnome_favorite_apps
      vars:
        gnome_favorite_apps:
          - org.gnome.Nautilus.desktop
          - terminator.desktop
          - google-chrome.desktop
          - chrome-elastisys.desktop
          - chrome-t.desktop
          - spotify_spotify.desktop
          - org.keepassxc.KeePassXC.desktop

    # Leave as last for proper cleanup
    - cklein.zz_cleanup
