- name: set up localhost as workstation
  hosts: localhost
  connection: local
  module_defaults:
    apt:
      force_apt_get: yes
    pip:
      executable: pip3
      extra_args: --user
  roles:
    # Must be first
    - cklein.00_bootstrap

    # These roles should be independent
    - cklein.cncf
    - cklein.remote_unlock_encrypted_volume
    - cklein.security
    - cklein.shell
    - cklein.vscode
    - workstation

    # Leave as last for proper cleanup
    - cklein.zz_cleanup
