- name: set up localhost as workstation
  hosts: localhost
  connection: local
  roles:
    - cklein.security
    - cklein.shell
    - cklein.vscode
    - workstation
    - remote_unlock_encrypted_volume
