---
- name: Install vim
  become: true
  ansible.builtin.apt:
    name:
      - ansible-lint
      - git
      - vim-gtk3

- name: Clone vim configuration
  ansible.builtin.git:
    repo: '{{ repos.vimrc }}'
    dest: ~/.vim
    depth: 1
    update: false
    version: master

- name: Link .vimrc to ~
  ansible.builtin.file:
    src: ~/.vim/.vimrc
    dest: ~/.vimrc
    state: link
