---
- name: Install vim
  become: true
  apt:
    name:
      - ansible-lint
      - git
      - vim-gtk3

- name: Configure default editor
  template:
    src: selected_editor.j2
    dest: ~/.selected_editor

- name: Clone vim configuration
  git:
    repo: '{{ repos.vimrc }}'
    dest: ~/.vim
    depth: 1
    update: no

- name: Link .vimrc to ~
  file:
    src: ~/.vim/.vimrc
    dest: ~/.vimrc
    state: link
