- name: Copy shell configuration files
  template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
  with_list:
    - bashrc
    - bash_aliases
    - bash_logout
    - profile
  tags:
    - wsl

- name: Remove unnecessary shell configuration files
  file:
    path: '~/.{{ item }}'
    state: absent
  with_list:
    - bash_profile
  tags:
    - wsl
