---
- name: Copy shell configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "~/.{{ item }}"
    mode: '0644'
  with_list:
    - bashrc
    - bash_aliases
    - bash_completion
    - bash_logout
    - inputrc
    - profile

- name: Remove unnecessary shell configuration files
  ansible.builtin.file:
    path: '~/.{{ item }}'
    state: absent
    mode: '0644'
  with_list:
    - bash_profile
