- name: "apt | ensure Google chrome repo present"
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.gpg] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: "google-chrome"
    update_cache: yes

- name: "apt | ensure Google chrome present"
  become: true
  apt:
    name: "google-chrome-stable"
