- name: Add Google Chrome repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/google.gpg] https://dl.google.com/linux/chrome/deb/ stable main"

- name: "Install Google Chrome"
  become: true
  apt:
    name:
      - google-chrome-stable
