---
- name: Install mutt
  become: true
  ansible.builtin.apt:
    name:
      - mutt
      - python3-keyring  # for securely storing passwords

- name: Create mutt config folder
  ansible.builtin.file:
    path: ~/.config/mutt
    state: directory
    mode: '0700'

- name: Copy configuration files
  ansible.builtin.template:
    src: '{{ item | basename | regex_replace("^[.]") }}.j2'
    dest: '{{ item }}'
    mode: '0644'
  loop:
    - ~/.config/mutt/muttrc
    - ~/.signature
