- name: Install basic tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - jq
    - mc
    - moreutils
    - pv
    - zip
  become: true
  tags:
    - wsl

- name: Configure .bashrc
  template: 
    src: bashrc.j2
    dest: $HOME/.bashrc
  tags:
    - wsl

- name: Configure .profile
  template: 
    src: profile.j2
    dest: $HOME/.profile
  tags:
    - wsl

