- name: Install basic tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - curl
    - mc
    - pv
    - vim

- name: Configure default editor
  template: 
    src: selected_editor.j2
    dest: $HOME/.selected_editor
  become: true

- name: Configure .profile
  template: 
    src: profile.j2
    dest: $HOME/.profile

