- name: Install awscli
  pip:
    name: awscli
    extra_args: --user
  tags:
    - wsl

- name: Install awscli shortcut
  file:
    src: "$HOME/.local/bin/aws"
    dest: "$HOME/bin/aws"
    state: link
  tags:
    - wsl

- name: Install google-cloud-sdk
  become: true
  command: snap install google-cloud-sdk --classic creates=/snap/bin/gcloud
