- name: Install awscli
  pip:
    name: awscli
    extra_args: --user
  tags:
    - wsl

- name: Install awscli shortcut
  file:
    src: "$HOME/.local/bin/aws"
    dest: "$HOME/bin/aws"
    state: link
  tags:
    - wsl

- name: Install google-cloud-sdk
  become: true
  command: snap install google-cloud-sdk --classic creates=/snap/bin/gcloud

- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
    dest: $HOME/bin/kubectl
    mode: 0775
  tags:
    - wsl
