- name: Install google-cloud-sdk
  become: true
  snap:
    name: google-cloud-sdk
    classic: yes

- include_tasks: cloud_tools/aws.yml
- include_tasks: cloud_tools/az.yml
- include_tasks: cloud_tools/k8s.yml
