- name: Install development tools
  apt:
    name:
    - build-essential
    - git
    - git-crypt
    - git-lfs
    - gitk
    - libtext-markdown-perl
    - meld
    - sloccount
    - subversion
  become: true

- name: Install gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Install tools (via pip)
  pip:
    name:
      - pipenv
      - pre-commit

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    creates: ~/.nvm/nvm.sh
