- name: Install development tools
  apt:
    name:
    - build-essential
    - ccache
    - libtext-markdown-perl
    - meld
    - sloccount
    - subversion
  become: true

- name: Install tools (via pip)
  pip:
    name:
      - pipenv

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    creates: ~/.nvm/nvm.sh
