- name: Install development tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - build-essential
    - git
    - git-crypt
    - git-lfs
    - gitk
    - libtext-markdown-perl
    - meld
    - sloccount
    - subversion
  become: true
  tags:
    - wsl

- name: Install gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig
  tags:
    - wsl

- name: Install tools (via pip)
  pip:
    name:
      - pipenv
      - pre-commit
  tags:
    - wsl

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    creates: ~/.nvm/nvm.sh
