- name: Install development tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - build-essential
    - git
    - git-crypt
    - libtext-markdown-perl
    - meld
    - python-pip
    - python3-pip
    - sloccount
  become: true
