- name: Install development tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - build-essential
    - git
    - git-crypt
    - gitk
    - libtext-markdown-perl
    - meld
    - sloccount
  become: true

- name: Install gitconfig
  template:
    src: gitconfig.j2
    dest: $HOME/.gitconfig

- name: Install pipenv
  pip:
    name: "{{ packages }}"
    extra_args: --user
  vars:
    packages:
    - pipenv
    
- name: Ensure $HOME/bin exists
  file:
    path: $HOME/bin
    state: directory

- name: Install pipenv shortcut
  file:
    src: $HOME/.local/bin/pipenv
    dest: $HOME/bin/pipenv
    state: link
