- name: Install docker
  become: true
  command: snap install docker creates=/snap/bin/docker

- name: "Add docker group"
  become: true
  group:
    name: docker
    system: yes
  notify:
    - restart-docker

- name: "Add the user {{ ansible_user_id }} to docker group"
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- stat: path=/var/run/docker.sock
  register: docker_sock

- name: restart-docker
  become: true
  command: "{{ item }}"
  with_items:
  - "snap disable docker"
  - "snap enable docker"
  when: (not docker_sock.stat.exists) or
        (not docker_sock.stat.gr_name == 'docker')
