- name: Install docker install prerequisites
  become: true
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

- name: Add Docker apt-key
  become: true
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: Add Docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"

- name: Install Docker
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-compose

- name: "Add docker group"
  become: true
  group:
    name: docker
    system: yes

- name: "Add the user {{ ansible_user_id }} to docker group"
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- stat: path=/var/run/docker.sock
  register: docker_sock

- name: restart-docker
  become: true
  command: "systemctl restart docker"
  when: (not docker_sock.stat.exists) or
        (not docker_sock.stat.gr_name == 'docker')
  tags:
    - systemd
