- name: "Create user applications and icons folder"
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
    - "~/.local/share/applications"
    - "~/.local/share/icons/hicolor/scalable/apps"

- name: "Install Chrome Elastisys icon"
  template:
    src: chrome-elastisys.svg.j2
    dest: ~/.local/share/icons/hicolor/scalable/apps/chrome-elastisys.svg

- name: "Install Chrome Elastisys Desktop file"
  template:
    src: chrome-elastisys.desktop.j2
    dest: ~/.local/share/applications/chrome-elastisys.desktop

- name: "Fix native integration for KeePassXC-browser"
  file:
    src: ~/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
    dest: ~/.config/google-chrome-elastisys/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
    state: link
