- name: Install GUI tools
  apt:
    name:
      - dconf-editor
  become: true

- name: Install Spotify
  become: true
  command: snap install spotify --classic creates=/snap/bin/spotify
  tags:
    - snap

- name: Install Slack
  become: true
  command: snap install slack --classic creates=/snap/bin/slack
  tags:
    - snap

- name: Install Thunderbird and Calendar
  become: true
  apt:
    pkg:
      - thunderbird
      - xul-ext-lightning
      - xul-ext-gdata-provider

- name: OpenSCAD
  become: true
  apt:
    pkg:
      - openscad

- name: Install ImageMagick
  become: true
  apt:
    pkg:
      - imagemagick

- name: Allow ImageMagick to rasterize PDFs
  become: true
  lineinfile:
    path: /etc/ImageMagick-6/policy.xml
    regex: domain.*coder.*pattern.*PDF
    line: '  <policy domain="coder" rights="read | write" pattern="PDF" />'
