- name: Install GUI tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dconf-editor
    - terminator
  become: true

- name: Install skype
  become: true
  command: snap install skype --classic creates=/snap/bin/skype

- name: Install Spotify
  become: true
  command: snap install spotify --classic creates=/snap/bin/spotify

- name: Install Slack
  become: true
  command: snap install slack --classic creates=/snap/bin/slack
