- name: Install GUI tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - dconf-editor
    - terminator
  become: true

- name: Install skype
  become: true
  command: snap install skype --classic creates=/snap/bin/skype

- name: Install Spotify
  become: true
  command: snap install spotify --classic creates=/snap/bin/spotify

- name: Install Slack
  become: true
  command: snap install slack --classic creates=/snap/bin/slack

- name: Configure terminator (folder)
  file:
    path: $HOME/.config/terminator
    recurse: yes
    state: directory

- name: Configure terminator
  template:
    src: terminator_config.j2
    dest: $HOME/.config/terminator/config

- name: Install Thunderbird and Calendar
  become: true
  apt:
    pkg:
      - thunderbird
      - xul-ext-lightning
      - xul-ext-gdata-provider

- name: OpenSCAD PPA
  become: true
  apt_repository:
    repo: ppa:openscad/releases
    codename: bionic

- name: OpenSCAD
  become: true
  apt:
    pkg:
      - openscad
