- name: Install GUI tools
  apt:
    name:
      - dconf-editor
      - terminator
  become: true

- name: Install Spotify
  become: true
  command: snap install spotify --classic creates=/snap/bin/spotify
  tags:
    - snap

- name: Install Slack
  become: true
  command: snap install slack --classic creates=/snap/bin/slack
  tags:
    - snap

- name: Configure terminator (folder)
  file:
    path: ~/.config/terminator
    recurse: yes
    state: directory

- name: Configure terminator
  template:
    src: terminator_config.j2
    dest: ~/.config/terminator/config

- name: Install Thunderbird and Calendar
  become: true
  apt:
    pkg:
      - thunderbird
      - xul-ext-lightning
      - xul-ext-gdata-provider

- name: OpenSCAD PPA
  become: true
  apt_repository:
    repo: ppa:openscad/releases
    codename: '{{ ansible_distribution_release }}'

- name: OpenSCAD
  become: true
  apt:
    pkg:
      - openscad

- name: Install ImageMagick
  become: true
  apt:
    pkg:
      - imagemagick

- name: Allow ImageMagick to rasterize PDFs
  become: true
  lineinfile:
    path: /etc/ImageMagick-6/policy.xml
    regex: domain.*coder.*pattern.*PDF
    line: '  <policy domain="coder" rights="read | write" pattern="PDF" />'
