- name: Install GUI tools
  apt:
    name:
      - dconf-editor
  become: true

- name: Install Spotify
  become: true
  command: snap install spotify --classic creates=/snap/bin/spotify
  tags:
    - snap

- name: Install Slack
  become: true
  command: snap install slack --classic creates=/snap/bin/slack
  tags:
    - snap
