- name: Install vim
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - vim-gtk3
  become: true
  tags:
    - wsl

- name: Configure default editor
  template:
    src: selected_editor.j2
    dest: ~/.selected_editor
  tags:
    - wsl

- name: Clone vim configuration
  git:
    repo: '{{ repos.vimrc }}'
    dest: ~/.vim
    depth: 1
    update: no
  tags:
    - wsl

- name: Link .vimrc to ~
  file:
    src: ~/.vim/.vimrc
    dest: ~/.vimrc
    state: link
  tags:
    - wsl
