- name: Install vim
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - vim-gtk3
  become: true
  tags:
    - wsl

- name: Configure default editor
  template:
    src: selected_editor.j2
    dest: $HOME/.selected_editor
  tags:
    - wsl

- name: Clone vim configuration
  git:
    repo: '{{ repos.vimrc }}'
    dest: $HOME/.vim
    depth: 1
    update: no
  tags:
    - wsl

- name: Link .vimrc to $HOME
  file:
    src: $HOME/.vim/.vimrc
    dest: $HOME/.vimrc
    state: link
  tags:
    - wsl
