---
- name: Install security tools
  ansible.builtin.apt:
    name:
      - gnupg2
      - gnupg-agent
      - passwordmaker-cli  # legacy, new passwords are on keepassx
      - pcscd
      - pinentry-curses
      - scdaemon
      - wipe
      - yubikey-personalization
  become: true
  tags:
    - gpg

- name: Install KeePassXC PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:phoerious/keepassxc
  tags:
    - keepassxc
  when: ansible_lsb.id == "Ubuntu" and ansible_lsb.major_release|int <= 20

- name: Install KeePassXC
  ansible.builtin.apt:
    name:
      - keepassxc
  become: true
  tags:
    - keepassxc

- name: Create gpg config folder
  ansible.builtin.file:
    path: ~/.gnupg
    state: directory
    mode: '0700'
  tags:
    - gpg

- name: Copy configuration files
  ansible.builtin.template:
    src: '{{ item | basename }}.j2'
    dest: '{{ item }}'
    mode: '0600'
  loop:
    - ~/.gnupg/gpg.conf
    - ~/.gnupg/gpg-agent.conf
    - ~/.gnupg/gpgkeys.txt
  tags:
    - gpg

- name: Import GPG keys
  ansible.builtin.shell: |
    set -ex

    gpg --import ~/.gnupg/gpgkeys.txt

    echo 'Setting up GPG private keys.' >&2
    echo 'This requires the SmartCard to be plugged in' >&2
    gpg --card-status

    echo "GPG keys imported at $(date -Is)" > ~/.gnupg/gpgkeys-imported.txt
  args:
    creates: ~/.gnupg/gpgkeys-imported.txt
  ignore_errors: true
  tags:
    - gpg

- name: Create SSH config folder
  ansible.builtin.file:
    path: ~/.ssh
    state: directory
    mode: '0700'
  tags:
    - ssh

- name: Configure SSH client
  ansible.builtin.template:
    src: 'ssh/{{ item | basename }}.j2'
    dest: '{{ item }}'
    mode: '0600'
  loop:
    - ~/.ssh/authorized_keys
    - ~/.ssh/config
    - ~/.ssh/id_rsa.pub
  tags:
    - ssh

- name: Setup ssh server
  ansible.builtin.apt:
    name:
      - openssh-server
      - fail2ban
  become: true
  tags:
    - ssh

- name: Do not send LANG via ssh
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/ssh_config
    backrefs: true
    regexp: '([^#]*)SendEnv(.*)'
    line: '#\1SendEnv\2'

- name: Configure PasswordMaker
  ansible.builtin.template:
    src: passwordmaker.rdf.j2
    dest: ~/.passwordmaker.rdf
    mode: '0600'

- name: Make home folder private for multi-user workstations
  ansible.builtin.file:
    path: ~/
    state: directory
    mode: '0700'
  tags:
    - privacy
