- name: Install security tools
  apt:
    name:
    - gnupg2
    - gnupg-agent
    - passwordmaker-cli # legacy, new passwords are on keepassx
    - pcscd
    - pinentry-curses
    - scdaemon
    - wipe
    - yubikey-personalization
    - yubikey-personalization-gui
  become: true
  tags:
    - gpg

- name: Install KeePassXC PPA
  become: true
  apt_repository:
    repo: ppa:phoerious/keepassxc
  tags:
    - keepassxc
  when: ansible_lsb.id == "Ubuntu" and ansible_lsb.major_release|int <= 20

- name: Install KeePassXC
  apt:
    name:
    - keepassxc
  become: true
  tags:
    - keepassxc

- name: Create gpg config folder
  file:
    path: ~/.gnupg
    state: directory
    recurse: true
    mode: 0700
  tags:
    - gpg

- name: Copy configuration files
  template:
    src: '{{ item | basename }}.j2'
    dest: '{{ item }}'
  loop:
    - ~/.gnupg/gpg.conf
    - ~/.gnupg/gpg-agent.conf
    - ~/.gnupg/gpgkeys.txt
  tags:
    - gpg

- name: Import GPG keys
  shell: |
    set -ex

    gpg --import ~/.gnupg/gpgkeys.txt

    echo 'Setting up GPG private keys. This requires the SmartCard to be plugged in' >&2
    gpg --card-status

    echo "GPG keys imported at $(date -Is)" > ~/.gnupg/gpgkeys-imported.txt
  args:
    creates: ~/.gnupg/gpgkeys-imported.txt
  ignore_errors: yes
  tags:
    - gpg

- name: Create SSH config folder
  file:
    path: ~/.ssh
    state: directory
    recurse: true
    mode: 0700
  tags:
    - ssh

- name: Configure SSH client
  template:
    src: 'ssh/{{ item | basename }}.j2'
    dest: '{{ item }}'
  loop:
    - ~/.ssh/authorized_keys
    - ~/.ssh/config
    - ~/.ssh/id_rsa.pub
  tags:
    - ssh

- name: Setup ssh server
  apt:
    name:
      - openssh-server
      - fail2ban
  become: true
  tags:
    - ssh

- name: Do not send LANG via ssh
  become: true
  lineinfile:
    path: /etc/ssh/ssh_config
    backrefs: true
    regexp: '([^#]*)SendEnv(.*)'
    line: '#\1SendEnv\2'
  tags:
    - ssh

- name: Configure PasswordMaker
  template:
    src: passwordmaker.rdf.j2
    dest: ~/.passwordmaker.rdf

- name: Make home folder private for multi-user workstations
  file:
    path: ~/
    state: directory
    mode: 0700
  tags:
    - privacy
