- name: Install development tools
  apt:
    name:
    - build-essential
    - ccache
    - libtext-markdown-perl
    - meld
    - sloccount
    - subversion
  become: true
  tags:
    - c

- name: Copy configuration files
  template:
    src: '{{ item | basename | regex_replace("^[.]") }}.j2'
    dest: '{{ item }}'
  loop:
    - ~/.ccache/ccache.conf
  tags:
    - c
