---
- name: Install development tools
  ansible.builtin.apt:
    name:
      - build-essential
      - ccache
      - libtext-markdown-perl
      - meld
      - sloccount
      - subversion
  become: true

- name: Create configuration folders
  ansible.builtin.file:
    path: ~/.ccache
    state: directory
    recurse: true
    mode: '0700'

- name: Copy configuration files
  ansible.builtin.template:
    src: '{{ item | basename | regex_replace("^[.]") }}.j2'
    dest: '{{ item }}'
    mode: '0644'
  loop:
    - ~/.ccache/ccache.conf
