---
- name: Update apt package
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe
  tags: update

- name: Remove useless packages from the cache
  ansible.builtin.apt:
    autoclean: true
  become: true

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
  become: true
