- name: Prefer binaries in ~/bin instead of deb packages
  become: true
  apt:
    name:
      - kubectx
    state: absent
    purge: true
  tags:
    - wsl

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: true
  tags:
    - wsl

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true
  tags:
    - wsl
