---
- name: Prefer binaries in ~/bin instead of deb packages
  become: true
  ansible.builtin.apt:
    name:
      - kubectx
    state: absent
    purge: true

- name: Remove Skype
  become: true
  ansible.builtin.command: snap remove skype removes=/snap/bin/skype
  tags:
    - snap

- name: Remove deprecated files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - ~/.mimeapps.list
    - ~/.xsessionrc

# https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key
- name: Remove certs in /etc/apt/trusted.gpg.d
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/apt/trusted.gpg.d/docker*"
    - "/etc/apt/trusted.gpg.d/google*"
    - "/etc/apt/trusted.gpg.d/microsoft*"
