---
- name: Prefer binaries in ~/bin instead of deb packages
  become: true
  ansible.builtin.apt:
    name:
      - kubectx
    state: absent
    purge: true

- name: Prefer pip only in virtual environments
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
    state: absent
    purge: true

- name: Remove Skype
  become: true
  community.general.snap:
    name: skype
    state: absent
  tags:
    - snap

- name: Remove deprecated files
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop:
    - ~/.mimeapps.list
    - ~/.xsessionrc

# https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key
- name: Remove certs in /etc/apt/trusted.gpg.d
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/etc/apt/trusted.gpg.d/docker*"
    - "/etc/apt/trusted.gpg.d/google*"
    - "/etc/apt/trusted.gpg.d/microsoft*"
