---
- name: Install chrony
  become: true
  ansible.builtin.apt:
    name:
      # Should remove systemd-timesyncd
      - chrony

- name: Setup ntp.se sources
  become: true
  ansible.builtin.copy:
    src: sources.d/
    dest: /etc/chrony/sources.d/
    directory_mode: '0755'
    mode: '0644'
  notify:
    - Reload chrony sources
