---
- name: Install git and tools
  ansible.builtin.apt:
    name:
      - git
      - git-crypt
      - git-lfs
      - gitk
      - pre-commit
  become: true

- name: Remove ~/.gitconfig
  ansible.builtin.file:
    path: ~/.gitconfig
    state: absent

- name: Create git config folder
  ansible.builtin.file:
    path: ~/.config/git
    state: directory
    mode: '0755'

- name: Configure git
  ansible.builtin.template:
    src: gitconfig.j2
    dest: ~/.config/git/config
    mode: '0644'

- name: Install git-checkall
  ansible.builtin.template:
    src: git-checkall.j2
    dest: ~/bin/git-checkall
    mode: '0755'
