- name: Install required packages
  apt:
    name:
      - dropbear-initramfs
      - cryptsetup
  become: true

# Ugly: https://bugs.launchpad.net/ubuntu/+source/busybox/+bug/1651818/comments/11
- name: Patch cryptsetup
  become: true
  patch:
    src: cryptroot-unlock-neutered-busybox-progs.patch
    basedir: /usr/share/cryptsetup/initramfs/bin/
    strip: 1
  when: ansible_distribution_release == 'bionic'
  notify: Update initramfs

- name: Configure dropbear in initramfs
  become: true
  lineinfile:
    path: /etc/dropbear-initramfs/config
    regexp: '^DROPBEAR_OPTIONS='
    insertafter: '^#DROPBEAR_OPTIONS='
    line: 'DROPBEAR_OPTIONS=-p8022'
    owner: root
    group: root
    mode: 0644
  notify: Update initramfs

- name: Create authorized_keys
  become: true
  template:
    src: 'ssh/authorized_keys.j2'
    dest: /etc/dropbear-initramfs/authorized_keys
    mode: 0644
  notify: Update initramfs
