---
- name: Install GUI tools
  ansible.builtin.apt:
    name:
      - terminator
  become: true

- name: Configure terminator (folder)
  ansible.builtin.file:
    path: ~/.config/terminator
    recurse: true
    state: directory
    mode: '0644'

- name: Configure terminator
  ansible.builtin.template:
    src: terminator_config.j2
    dest: ~/.config/terminator/config
    mode: '0644'
