- name: Install GUI tools
  apt:
    name:
      - terminator
  become: true

- name: Configure terminator (folder)
  file:
    path: ~/.config/terminator
    recurse: yes
    state: directory

- name: Configure terminator
  template:
    src: terminator_config.j2
    dest: ~/.config/terminator/config
