- name: Create folder for fonts
  file:
    path: '~/.local/share/fonts/'
    state: directory
  tags:
    - fonts

- name: Install Fonts
  copy:
    src: '.'
    dest: '~/.local/share/fonts/'
  tags:
    - fonts
  notify:
    - Reset font cache
