- name: "apt | ensure Google linux signing key present"
  become: true
  apt_key:
    id: 4CCA1EAF950CEE4AB83976DCA040830F7FAC5991
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/keyrings/google.gpg
