---
- name: Mount tmpfs as /tmp
  ansible.posix.mount:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noatime,size=25%,mode=1777
    state: mounted
  become: true
  tags:
    - mount
