- name: Install python3 development tools (via apt)
  become: true
  apt:
    name:
      - python3-venv

- name: Install python3 development tools (via pip)
  pip:
    name:
      - pylint ~= 2.6
    state: latest
