---
- name: Install ImageMagick
  become: true
  ansible.builtin.apt:
    pkg:
      - imagemagick

- name: Allow ImageMagick to rasterize PDFs
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ImageMagick-6/policy.xml
    regex: domain.*coder.*pattern.*PDF
    line: '  <policy domain="coder" rights="read | write" pattern="PDF" />'
  when: imagemagick_allow_rasterize_any_pdf | bool
