---
- name: Download zoom.deb
  ansible.builtin.get_url:
    url: 'https://zoom.us/client/{{ zoom_version }}/zoom_amd64.deb'
    dest: /tmp/zoom.deb
    checksum: '{{ zoom_checksum }}'
    mode: '0644'

- name: Install Zoom
  become: true
  ansible.builtin.apt:
    deb: /tmp/zoom.deb
