- name: Add Microsoft repository
  become: true
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main

- name: Install .NET packages
  become: true
  apt:
    pkg: '{{ dotnet_pkgs }}'
