- name: Install prerequisites
  become: true
  apt:
    pkg:
      - apt-transport-https

- name: Add Microsoft key
  become: true
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: 'https://packages.microsoft.com/keys/microsoft.asc'

- name: Add Microsoft repository
  become: true
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main

- name: Install .NET packages
  become: true
  apt:
    pkg: '{{ dotnet_pkgs }}'
