---
- name: Create wallpapers folder
  ansible.builtin.file:
    name: ~/Pictures/Wallpapers
    state: directory
    mode: '0755'

- name: Copy wallpapers
  ansible.posix.synchronize:
    src: .
    dest: ~/Pictures/Wallpapers

- name: Get path to wallpaper
  ansible.builtin.set_fact:
    wallpaper_path: ~/Pictures/Wallpapers/{{ wallpaper }}

- name: Set GNOME Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "{{ wallpaper_path | expanduser | tojson }}"
  tags:
    - dconf
