- name: Create wallpapers folder
  file:
    name: ~/Pictures/Wallpapers
    state: directory

- name: Copy wallpapers
  copy:
    src: .
    dest: ~/Pictures/Wallpapers

- name: Get path to wallpaper
  ansible.builtin.set_fact:
    wallpaper_path: ~/Pictures/Wallpapers/{{ wallpaper }}

- name: Set GNOME Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "{{ wallpaper_path | expanduser | tojson }}"
