- name: Create wallpapers folder
  file:
    name: ~/Pictures/Wallpapers
    state: directory

- name: Copy wallpapers
  copy:
    src: .
    dest: ~/Pictures/Wallpapers

- name: Set GNOME Wallpaper
  community.general.dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: '"$HOME/Pictures/Wallpapers/{{ wallpaper }}"'
