- name: Install awscli
  pip:
    name: awscli

- name: Install aws-iam-authenticator
  get_url:
    url: https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/linux/amd64/aws-iam-authenticator
    dest: ~/bin/aws-iam-authenticator
    mode: 0755
