- name: Install kubectl
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl
    dest: $HOME/bin/kubectl
    mode: 0775
  tags:
    - wsl

- name: Install helm
  become: true
  snap:
    name: helm
    classic: yes
