name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: cache pre-commit deps
        id: cache_pre_commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
      - run: pre-commit run --all
