name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        role:
          - ''
          - cklein.cloud_tools
          - cklein.cncf
          - cklein.git
          - cklein.go
          - cklein.security
          - cklein.shell

    env:
      ROLE: ${{ matrix.ROLE }}

    steps:
      - uses: actions/checkout@v2

      - name: Generate Site YAML for Role
        run: |
          ./scripts/generate-site-yml-for-role.sh
          cat site.yml

      - name: Test Role
        run: ./test.sh
