---
name: Test
'on': push

env:
  DOCKER_IMAGE: "cristiklein/stateless-workstation-config/ubuntu-desktop"

jobs:
  test:
    name: Test roles
    runs-on: ubuntu-latest

    strategy:
      matrix:
        role:
          - ''
          - cklein.cloud_tools
          - cklein.cncf
          - cklein.dotfiles
          - cklein.git
          - cklein.go
          - cklein.security
        ubuntu_version:
          - '24.04'
          - '24.10'

    env:
      ROLE: ${{ matrix.ROLE }}
      UBUNTU_VERSION: ${{ matrix.UBUNTU_VERSION }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: actions/checkout@v4

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          # This should be equivalent to ./build.sh, but levarage GitHub Actions
          # Cache.
          context: .
          tags: "${{ env.DOCKER_IMAGE }}:${{ matrix.UBUNTU_VERSION }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # yamllint disable-line rule:line-length
          outputs: type=docker

      - name: Generate Site YAML for Role
        run: |
          ./scripts/generate-site-yml-for-role.sh
          cat site.yml

      - name: Test Role
        run: ./test.sh
